#!/bin/bash

BK=$(tput setaf 0)   # Black
RD=$(tput setaf 1)   # Red
GR=$(tput setaf 2)   # Green
YW=$(tput setaf 3)   # Yellow
BL=$(tput setaf 4)   # blue
PP=$(tput setaf 5)   # purple
CY=$(tput setaf 6)   # Cyan
WH=$(tput setaf 7)   # White
MR=$(tput setaf 9)   # merahmuda
KN=$(tput setaf 11)  # kuning
BL1=$(tput setaf 12) # birublink
PK=$(tput setaf 13)  # pink
BLC=$(tput setaf 16) # black
BD=$(tput bold)      # Bold
NC=$(tput sgr0)
tir="$KN --->$NC"
done="$GR[$RD✘$GR]$NC"
plus="$GR[$RD+$GR]$NC"
error="$GR[$RD!$GR]$NC"


export PATH=$PATH:/root/bins/
mainpath=/root
toolspath=/root/colabhacks
bar="---------------------------------------"

echo -e "\n$bar\n\tSubdomains Enumerator\n$bar\n"
read -p "Please enter target (i.e. site.com): " host

HOST=$domain
domain=$host
sublist3rPATH=/root/results/$domain-sublist3r.txt
subfinderPATH=/root/results/$domain-subfinder.txt
amassPATH=/root/results/$domain-amass.txt
oneForAllPATH=/root/results/
assetfinderPATH=/root/results/$domain-assetfinder.txt
finddomainPATH=/root/results/$domain-findomain.txt

# Maintaining social distancing between vars and funcs :)
# UwU 

function automateSublist3r() {
	echo -e "$CY[+] Now running$RD Sublist3r$NC"
	cd $mainpath
	cd Sublist3r/
	python3 sublist3r.py -d $domain -n -t 10 | grep -Po "[\w-.]*$domain" | grep -v "Enumerating*" | sed 's/\[-\] //g' | tee /root/results/$domain-sublist3r.txt
	echo -e "$done$RD Sublist3r$CY found$tir $GR[ $(cat /root/results/$domain-sublist3r.txt | wc -l) ]$NC"
}

function automateSubfinder() {
	echo -e "$CY[+] Now running$RD Subfinder$NC"
	cd $toolspath
	subfinder -o /root/results/$domain-subfinder.txt -all -t 100 -silent -d $domain 
	echo -e "$done$RD Subfinder$CY found$tir $GR[ $(cat /root/results/$domain-subfinder.txt | wc -l) ]$NC"
}

function automateAmass() {
	echo -e "$CY[+] Now running$RD Amass$NC"
	cd $toolspath
	amass enum -passive -o /root/results/$domain-amass.txt -d $domain -nolocaldb -norecursive -timeout 8 -nocolor
	echo -e "$done$RD Amass$CY found$tir $GR[ $(cat /root/results/$domain-amass.txt | wc -l) ]$NC"
}

function automateAssetsFinder() {
	echo -e "$CY[+] Now running$RD Assetfinder$NC"
	cd $toolspath
	assetfinder --subs-only $domain | tee /root/results/$domain-assetfinder.txt
	echo -e "$done$RD Assetfinder$CY found$tir $GR[ $(cat /root/results/$domain-assetfinder.txt | wc -l) ]$NC"
}

function automateFindomain() {
	echo -e "$CY[+] Now running$RD Findomain$NC"
	cd $toolspath
	findomain -t $domain -u /root/results/$domain-findomain.txt -q
	echo -e "$done$RD Findomain$CY found$tir $GR[ $(cat /root/results/$domain-findomain.txt | wc -l) ]$NC"
}

function automateSubhunt() {
	echo -e "$CY[+] Now running$RD Subhunt$NC"
	cd $toolspath
	bash subhunt $domain | tee /root/results/$domain-subhunt.txt
	echo -e "$done$RD Subhunt$CY found$tir $GR[ $(cat /root/results/$domain-subhunt.txt | wc -l) ]$NC"
}

function automateOneForAll() {
	echo -e "$CY[+] Now running$RD OneForAll$NC"
	cd /root/OneForAll/
	#cd OneForAll/
	python3 oneforall.py --target $HOST run --path=/root/results/
	cat /root/results/$domain.csv | cut -d "," -f6 | tee /root/results/$domain-oneforall.txt
	rm -rf $mainpath/results/*.csv
	echo -e "$done$RD Subhunt$CY found$tir $GR[ $(cat /root/results/$domain-oneforall.txt | wc -l) ]$NC"
}


function sortResults() {
	cd /root/results/
	cat *.txt | sort -u > results
	rm -fr *.txt
	echo -e "$done$RD Total Subdomain$CY found$tir $GR[ $(cat /root/results/results | wc -l) ]$NC"


	echo -e "\n$bar\nFinal Results:\n$bar\n"
	echo -e "[#] Subdomains Count: $(wc -l < results.txt)\n"

	cat results.txt
}

# function resolveSubdomains() {
# 	cd /root/massdns/
# 	cat /root/results/results.txt | /root/massdns/bin/massdns -r /root/massdns/lists/resolvers.txt --quiet -t A -o S -w /root/massdns/results-resolved.txt

# 	echo -e "\n$bar\nResolved Results:\n$bar\n"
# 	echo -e "[#] Resolved Count: $(wc -l < /root/massdns/results-resolved.txt)\n"
# 	cat /root/massdns/results-resolved.txt
# }

automateSublist3r $domain
automateSubfinder $domain
automateAmass $domain
automateOneForAll $domain
automateAssetsFinder $domain
automateFindomain $domain
automateSubhunt $domain

sortResults
#resolveSubdomains
