#!/bin/bash

BK=$(tput setaf 0)   # Black
RD=$(tput setaf 1)   # Red
GR=$(tput setaf 2)   # Green
YW=$(tput setaf 3)   # Yellow
BL=$(tput setaf 4)   # blue
PP=$(tput setaf 5)   # purple
CY=$(tput setaf 6)   # Cyan
WH=$(tput setaf 7)   # White
MR=$(tput setaf 9)   # merahmuda
KN=$(tput setaf 11)  # kuning
BL1=$(tput setaf 12) # birublink
PK=$(tput setaf 13)  # pink
BLC=$(tput setaf 16) # black
BD=$(tput bold)      # Bold
NC=$(tput sgr0)
tir="$KN --->$NC"
done="$GR[$RD✘$GR]$NC"
plus="$GR[$RD+$GR]$NC"
error="$GR[$RD!$GR]$NC"

export PATH=$PATH:/root/bins/
bar="---------------------------------------"

echo -e "\n$bar\n\tSubdomains Enumerator\n$bar\n"
read -p "Please enter target (i.e. site.com): " host

domain=$host

function automateSublist3r() {
	echo -e "$CY[+] Now running$RD Sublist3r$NC"
	cd /root/Sublist3r/
	python3 sublist3r.py -d $domain -n -t 10 | grep -Po "[\w-.]*$domain" | grep -v "Enumerating*" | sed 's/\[-\] //g' | tee /root/results/$domain-sublist3r.txt
	echo -e "$done$RD Sublist3r$CY found$tir $GR[ $(cat /root/results/$domain-sublist3r.txt | wc -l) ]$NC"
}

function automateOneForAll() {
	echo -e "$CY[+] Now running$RD OneForAll$NC"
	cd /root/OneForAll/
	python3 oneforall.py --target $domain run --path=/root/results/
	cat /root/results/$domain.csv | cut -d "," -f6 | tee /root/results/$domain-oneforall.txt
	rm -rf /root//results/*.csv
	echo -e "$done$RD OneForAll$CY found$tir $GR[ $(cat /root/results/$domain-oneforall.txt | wc -l) ]$NC"
}

function automateSubfinder() {
	echo -e "$CY[+] Now running$RD Subfinder$NC"
	cd /root/colabhacks/
	./subfinder -o /root/results/$domain-subfinder.txt -all -t 100 -silent -d $domain
	echo -e "$done$RD Subfinder$CY found$tir $GR[ $(cat /root/results/$domain-subfinder.txt | wc -l) ]$NC"
}

function automateAmass() {
	echo -e "$CY[+] Now running$RD Amass$NC"
	cd /root/colabhacks/
	./amass enum -passive -o /root/results/$domain-amass.txt -d $domain -nolocaldb -norecursive -timeout 8 -nocolor
	echo -e "$done$RD Amass$CY found$tir $GR[ $(cat /root/results/$domain-amass.txt | wc -l) ]$NC"
}

function automateAssetsFinder() {
	echo -e "$CY[+] Now running$RD Assetfinder$NC"
	cd /root/colabhacks/
	./assetfinder --subs-only $domain | tee /root/results/$domain-assetfinder.txt
	echo -e "$done$RD Assetfinder$CY found$tir $GR[ $(cat /root/results/$domain-assetfinder.txt | wc -l) ]$NC"
}

function automateFindomain() {
	echo -e "$CY[+] Now running$RD Findomain$NC"
	cd /root/colabhacks/
	./findomain -t $domain -u /root/results/$domain-findomain.txt -q
	echo -e "$done$RD Findomain$CY found$tir $GR[ $(cat /root/results/$domain-findomain.txt | wc -l) ]$NC"
}

function automateSubhunt() {
	echo -e "$CY[+] Now running$RD Subhunt$NC"
	cd /root/colabhacks/
	bash subhunt $domain | tee /root/results/$domain-subhunt.txt
	echo -e "$done$RD Subhunt$CY found$tir $GR[ $(cat /root/results/$domain-subhunt.txt | wc -l) ]$NC"
}

# function resolveSubdomains() {
# 	cd /root/results/
# 	cat /root/colabhacks/subwordlist.txt | while read x;do echo "$x.$domain" >>/root/results/unresolved
# 	puredns resolve /root/results/unresolved -l 1000 --rate-limit-trusted 500 -r /root/colabhacks/resolvers.txt -q -w /root/results/$domain-puredns.txt
# 	#cat unresolved | /root/colabhacks/puredns -r /root/colabhacks/resolvers.txt --quiet -t A -o S -w /root/results/results-resolved.txt
# 	rm -fr /root/results/unresolved
# 	echo -e "$done$RD Puredns$CY found$tir $GR[ $(cat /root/results/results-resolved.txt | wc -l) ]$NC"
# }

function sortResults() {
	cd /root/results/
	cat *.txt | sort -u >results
	rm -fr *.txt

	## second level domain finding
	echo "$RD second level domain finding$NC"
	cat results | grep -Eo '[^.]+[^.]+\.[^.]+\.[^.]+$' | sed 's/^[*]//g' | sed 's/^[.]//g' | sed 's/^[-]//g' | sed '/^$/d' | grep -Po "[\w-.]*$domain" | tee secondsubs.txt
	cat secondsubs.txt | xargs -P50 -i{} sh -c '/root/colabhacks/assetfinder --subs-only {}' | sed '/^$/d' | tee secassetfinder.txt
	cat secondsubs.txt | xargs -P20 -i{} sh -c '/root/colabhacks/subfinder -d {} -t 100 -silent' | sed '/^$/d' | tee secsubfinder.txt
	cat secondsubs.txt | xargs -P20 -i{} sh -c '/root/colabhacks/findomain -t {} -q --http-retries 2' 2>/dev/null | sed '/^$/d' | tee secfindomain.txt

	## second level domain finding
	echo "$RD Third level domain finding$NC"
	cat * | grep -Eo '[^.]+\.[^.]+\.[^.]+\.[^.]+$' | sed 's/^[*]//g' | sed 's/^[.]//g' | sed 's/^[-]//g' | sed '/^$/d' | grep -Po "[\w-.]*$domain" | tee thirdsubs.txt
	cat thirdsubs.txt | xargs -P50 -i{} sh -c '/root/colabhacks/assetfinder --subs-only {}' | sed '/^$/d' | tee thiedassetfinder.txt
	cat thirdsubs.txt | xargs -P20 -i{} sh -c '/root/colabhacks/subfinder -d {} -t 100 -silent' | sed '/^$/d' | tee thirdsubfinder.txt
	cat thirdsubs.txt | xargs -P20 -i{} sh -c '/root/colabhacks/findomain -t {} -q --http-retries 2' 2>/dev/null | sed '/^$/d' | tee thirdfindomain.txt

	## forth level domain finding
	echo "$RD Forth level domain finding$NC"
	cat * | grep -Eo '[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+$' | sed 's/^[*]//g' | sed 's/^[.]//g' | sed 's/^[-]//g' | sed '/^$/d' | grep -Po "[\w-.]*$domain" | tee forthsubs.txt
	cat forthsubs.txt | xargs -P50 -i{} sh -c '/root/colabhacks/assetfinder --subs-only {}' | sed '/^$/d' | tee forthassetfinder.txt
	cat forthsubs.txt | xargs -P20 -i{} sh -c '/root/colabhacks/subfinder -d {} -t 100 -silent' | sed '/^$/d' | tee forthsubfinder.txt
	cat forthsubs.txt | xargs -P20 -i{} sh -c '/root/colabhacks/findomain -t {} -q --http-retries 2' 2>/dev/null | sed '/^$/d' | tee forthfindomain.txt

	## fivth level domain finding
	echo "$RD Forth level domain finding$NC"
	cat * | grep -Eo '[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+\.[^.]+$' | sed 's/^[*]//g' | sed 's/^[.]//g' | sed 's/^[-]//g' | sed '/^$/d' | grep -Po "[\w-.]*$domain" | tee fivthsubs.txt
	cat fivthsubs.txt | xargs -P50 -i{} sh -c '/root/colabhacks/assetfinder --subs-only {}' | sed '/^$/d' | tee fivthassetfinder.txt
	cat fivthsubs.txt | xargs -P20 -i{} sh -c '/root/colabhacks/subfinder -d {} -t 100 -silent' | sed '/^$/d' | tee fivthsubfinder.txt
	cat fivthsubs.txt | xargs -P20 -i{} sh -c '/root/colabhacks/findomain -t {} -q --http-retries 2' 2>/dev/null | sed '/^$/d' | tee fivthfindomain.txt

	cat * | sort -u >>$domain.txt
	echo -e "$done$RD Total Subdomain$CY found$tir $GR[ $(cat $domain.txt | wc -l) ]$NC"
}

automateSublist3r $domain
automateOneForAll $domain
automateSubfinder $domain
automateAmass $domain
automateAssetsFinder $domain
automateFindomain $domain
automateSubhunt $domain

sortResults
#resolveSubdomains
